# Generated by Django 5.0.6 on 2024-06-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_uploadedfile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
