# Generated by Django 5.0.6 on 2024-06-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_uploadedfile_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='json_data',
        ),
    ]
