# Generated by Django 5.0.6 on 2024-06-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_uploadedfile_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='json_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
