# Generated by Django 5.0.6 on 2024-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_uploadedfile_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
